version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - my-app-network
    volumes:
      - <directory path to upload the images>:<directory path to upload the images>
    environment:
      - BASE_UPLOAD_DIR=<directory path to upload the images>

  frontend:
    build:
      context: ./frontend_ui
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    networks:
      - my-app-network
    depends_on:
      - backend
    volumes:
      - <directory path of the indexed images>:<directory path of the indexed images>

networks:
  my-app-network:
    driver: bridge